#!/usr/bin/env bash
#This Bash script transfers a file from our client to a server.

path=$1
ip_add=$2
u_name=$3
key_path=$4

if [ $# -lt 3 ];
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no "$path" "$ip_add"@"$u_name":"$key_path"
fi
