#!/usr/bin/env bash
# This Bash script transfers a file from our client to a server.
# The script accepts 4 argument
#+   The path to the file to be transferred
#+   The IP of the server we want to transfer the file to
#+   The username scp connects with
#+   The path to the SSH private key that scp uses

path=$1
ip_add=$2
u_name=$3
file=$4

if [ $# -lt 3 ];
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$file" "$path" "$ip_add"@"$u_name":~
fi
