#!/usr/bin/env bash
# This script installs NGINX server and configures it to listen on port 80

sudo apt-get update
sudo apt-get install nginx -y

# Open port 80 in firewall
sudo ufw allow 'Nginx HTTP'

# Set Nginx configuration
echo "server {
    listen 80;
    location / {
	        echo 'Hello World!'
    }
}" | sudo tee /etc/nginx/sites-available/default
# Restart Nginx
sudo /etc/init.d/nginx restart
