#!/usr/bin/env bash
#This script installs an enginx server with the below configuration requirements:
#+  Installs nginx and make it listen on port 80
#+  Returns "Hello World" when querried at its root with a#+  GET request.
#+  configures /redirect_me as "301 moved permanently"
#+  Includes a custom 404 page containing "Ceci n'est pas une page".
#+  Configures Nginx so that its HTTP response from sever #+  'web-01' and server 'web-02' contains a custom header.
#+  The custom header must be 'X-Served-By'.
#+  Its value will be the hostname of the server nginx is running on.

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
