#!/usr/bin/env bash
#This script Installs and configure HAproxy on load balancer server 'lb-01' with the following requirements:
#+    HAProxy is configured to send traffic to 'web-01'
#+    and 'web-02'.
#+    load balancer distributes requests using round robin#+    algorithm.
#+    HAproxy can be managed via an init script.

apt-get update
apt-get -y upgrade

#Enabling a dedicated HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.7
apt-get update

#Install HAProxy
apt-get -y install haproxy=2.7.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 121905-web-01 54.210.10.180:80 check
    server 121905-web-02 54.237.42.211:80 check
" >> /etc/haproxy/haproxy.cfg

#start HAProxy
service haproxy start
